version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_SERVER_ID=1
      - ZOOKEEPER_TICK_TIME=2000
      - ZOOKEEPER_INIT_LIMIT=10
      - ZOOKEEPER_SYNC_LIMIT=5
    networks:
      datapipeline:
        ipv4_address: 10.0.0.2


  kafka:
    image: confluentinc/cp-kafka:7.2.1
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
      - "9999:9999"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_JMX_PORT=9999
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_LOG_RETENTION_MS=60000
      - CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS=kafka:9092
      - CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT=zookeeper:2181
      - CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS=1
      - CONFLUENT_METRICS_ENABLE=false
    depends_on:
      - zookeeper
    networks:
      datapipeline:
        ipv4_address: 10.0.0.3


  cassandra:
    image: cassandra:4.0.5
    container_name: cassandra
    hostname: cassandra
    healthcheck:
      test: [ "CMD", "cqlsh", "-e", "describe keyspaces" ]
      interval: 5s
      timeout: 5s
      retries: 60
    ports:
      - '9042:9042'
    networks:
      datapipeline:
        ipv4_address: 10.0.0.4
    volumes:
      - ./data/cassandra:/var/lib/cassandra


  kafka-stock:
    build:
      context: .
      dockerfile: Dockerfile
    image: kafka_stock:latest
    command: /bin/bash -c "echo 'Initializing servers...' && ~/kafka_stock/entrypoint.sh"
    ports:
      - '8080:8080' # Airflow webserver port
      - '5006:5006' # Bokeh server port
    restart: on-failure
    volumes:
      - .:/home/sthapa/kafka_stock
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    depends_on:
      - zookeeper
      - kafka
      - cassandra
    networks:
      datapipeline:
        ipv4_address: 10.0.0.5

networks:
  datapipeline:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/28